version: '3.1'

volumes:
  images:
  db:

services:
  db:
    image: mariadb:latest
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: chevereto

  chevereto:
    image: rdfriedl/docker-chevereto:latest
    depends_on:
    - db
    ports:
    - 8080:80
    volumes:
    - images:/var/www/html/images
    command: bash -c "chown www-data:www-data /var/www/html/images && apache2-foreground"
    environment:
      CHEVERETO_DB_HOST: db
      CHEVERETO_DB_USERNAME: root
      CHEVERETO_DB_PASSWORD: example
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_DB_PREFIX: chv_

  node:
    image: rdfriedl/chevereto-api:latest
    ports:
      - 80:3000
    environment:
      - NODE_ENV=production
      - CHEVERETO_DB_URL=mysql://root:example@db/chevereto
    deploy:
      replicas: 2
